### PR TITLE
Work around Django bug regarding column alias index numbering for subqueries.

### PR DESCRIPTION
**Pull request by sha-red**
Apologies for the minimal pull request without any tests and such. Commit early.

### CODE REVIEW

**Comment by matthiask** [comment]
Hi @sha-red 

Looks good and makes sense. I'd appreciate a unittest very much, since this area of the code is somewhat hacky.

**Comment by matthiask** [comment]
Hmm; maybe this is superseeded by #26 and its fix, #42?

**Comment by sha-red** [comment]
From a quick test with the current version 0.11 this commit indeed seems superseeded.

I'm sorry for the minimal collaboration, I have currently only minimal resources (might hopefully change again in the future.

**Comment by matthiask** [comment]
Don't worry! All contributions are worthwhile. Thanks for checking again.

**Pull request closed without merging**
